package com.common;

public class EmailNotificationSettingFunction
{
  public static enum FunctionNames
  {
    APPLICANT_REVIEW,  APPLICANT_REVIEW_FEEDBACK,  APPLICANT_ON_HOLD,  ADD_COMMENT_ON_APPLICANT,  OFFER_APPROVE_REJECT,  SEND_FOR_OFFER_APPROVAL,  QUESTIONANIRE_SUBMIT_TO_APPLICANT,  EXAM_SCHEDULE_TO_APPLICANT,  APPLICANT_SUBMIT,  APPLICANT_MOVE,  APPLICANT_MARK_DELETE,  APPLICANT_MARK_UNDO_DELETE;
    
    private FunctionNames() {}
  }
  
  public static enum ReqFunctionNames
  {
    REQUISITION_CREATION,  INITIATE_APPROVAL_REQUISITION,  CLOSE_REQUISITION,  DELETE_REQUISITION,  RECALL_REQUISITION,  APPROVE_REQUISITION,  REJECT_REQUISITION,  REASSIGN_REQUISITION_APPROVAL;
    
    private ReqFunctionNames() {}
  }
}
