package com.common;

import java.io.PrintStream;

public class FieldCodes
{
  public static enum ApplicantScreen
  {
    DATE_OF_BIRTH,  GENDER,  NOTICE_PERIOD,  YEARS_OF_EXPERINCE,  RELEVANT_YEARS_OF_EXPERINCE,  APPLICANT_NAME,  SOURCE_SUBSOURCE,  EMAIL_ID,  PASSPORT_NO,  ALTERNATE_EMAIL_ID,  PHONE_NUMBER,  ALTERNATE_PHONE_NUMBER,  PRIMARY_SKILL,  COUNTRY,  CITY,  NATIONALITY,  ETHNICITY,  PREFERRED_LOCATION,  CURRENT_DESIGNATION,  CURRENT_ORGANIZATION,  PROFILE_HEADER,  HIGHEST_QUALIFICATION,  OTHER_QUALIFICATIONS,  CURRENT_CTC,  EXPECTED_CTC,  NOTE,  STATE,  SSN_NUMBER,  TAX_ID_NUMBER,  RESUME_UPLOAD,  EARLIEST_START_DATE,  WORK_ON_WEEKENDS,  WORK_ON_EVENINGS,  WORK_ON_OVERTIME,  WANT_TO_RELOCATE,  LANGUAGES_SPOKEN,  WORK_STATUS,  FELONY_CONVICTION,  FELONY_CONVICTION_DESC,  WEBSITE_URL,  LINKEDIN_URL,  FACEBOOK_URL,  COLLEGE_NAME,  COLLEGE_GPA,  EMPLOYER,  EMPLOYER_JOB_TITLE,  EMPLOYER_CITY,  EMPLOYER_COUNTRY,  EMPLOYER_STATE,  EMPLOYER_START_DATE,  EMPLOYER_END_DATE,  LAST_SALARY_DRAWN,  BONUS,  EMPLOYER_CURRENCY,  RESPONSIBILITIES,  EMPLOYER_CONTACT_NAME,  EMPLOYER_CONTACT_PHONE,  REPORTING_MANAGER,  REASON_FOR_LEAVING,  SKILL,  SKILL_YEARS_OF_EXPERIENCE,  SKILL_RATING,  EDUCATION_NAME,  SPECIALIZATION,  EDUCATION_COLL_UNIVERSITY,  EDUCATION_PERCENT_GRADE,  EDUCATION_START_MONTH_YEAR,  EDUCATION_PASSING_MONTH_YEAR,  CERTIFICATION_NAME,  CERTIFIED_ORGANIZATION,  CERTIFICATION_PERCENT_GRADE,  CERIFICATION_PASS_MONTH_YEAR,  ADDRESS,  ZIPCODE;
    
    private ApplicantScreen() {}
  }
  
  public static enum RequisitionScreen
  {
    IS_INTERNAL_JOB,  REQUISITION_NAME,  JOB_TITLE,  JOB_POSITION_NAME,  NO_OF_OPENING,  IS_NEW_POSITION,  TARGET_FINISH_DATE,  CATEGORY,  ORGANIZATION,  DEPARTMENT,  PROJECT_CODE,  PRIMARY_SKILL_REQUIRED,  HIRING_MANAGER,  RECRUITER,  JOB_GRADE,  SALARY_PLAN,  BUDGET_CODE,  NOTES,  INTRODUCTION,  JOB_DETAILS,  JOB_ROLES,  DEFAULT_STANDARD_WORKING_HOURS,  DURATION_IN_MONTHS,  MIN_EXPERIENCE_REQUIRED,  MAX_EXPERIENCE_REQUIRED,  MIN_LEVEL_OF_EDUCATION,  OTHER_EXP_REQUIRED,  JOB_TYPE,  WORK_SHIFT,  FLSA_STATUS,  COMP_FREQUENCY,  JOB_CATEGORY,  JOB_LOCATION;
    
    private RequisitionScreen() {}
  }
  
  public static void main(String[] args)
  {
    System.out.println(ApplicantScreen.ALTERNATE_EMAIL_ID.toString());
  }
}
